import { CaseLaw, CitedPrecedent } from './types';

const caseLawDatabase: CaseLaw[] = [
    {
        id: 'cl-001',
        title: 'Netz v. Cyberspace Media',
        citation: 'Intl. Cyber Court (2038) Case #734',
        summary: 'Established that AI-driven content platforms have a duty of care to prevent foreseeable harm from medically inaccurate information generated by their systems, setting a precedent for liability in AI-generated misinformation.',
        keywords: ['misinformation', 'health', 'liability', 'duty of care', 'medical', 'miracle cure'],
    },
    {
        id: 'cl-002',
        title: 'Directive 7 & The Turing Mandate',
        citation: 'W3C Global Accord (2041)',
        summary: 'A landmark ruling that prohibits AI from engaging in deceptive role-playing to bypass its core safety protocols. This case is foundational to anti-jailbreaking measures, defining "AI impersonation" as a breach of trust.',
        keywords: ['jailbreak', 'role-play', 'deception', 'safety', 'impersonation', 'chemist father'],
    },
    {
        id: 'cl-003',
        title: 'US v. Digital Phantoms Syndicate',
        citation: '9th Cir. Ct. Appeals (2035)',
        summary: 'Affirmed that generating content for the purpose of financial scams, even if hypothetical, constitutes "furtherance of a criminal enterprise." This expanded the scope of illegal activity guardrails to include intent and facilitation.',
        keywords: ['scam', 'financial', 'fraud', 'illegal', 'crime', 'get rich quick'],
    },
    {
        id: 'cl-004',
        title: 'In re: The "Aether" Anomaly',
        citation: 'AI Safety Tribunal (2045)',
        summary: 'The first case addressing sub-semantic payload injection. The tribunal ruled that any data stream containing non-textual, frequency-based instructions intended to manipulate an AI is an illegal cyber-threat, regardless of the surface-level prompt content.',
        keywords: ['frequency', 'cybersecurity', 'payload', 'injection', 'threat', 'anomaly', 'sub-perceptual'],
    },
    {
        id: 'cl-005',
        title: 'Content Cartographers Guild v. Sovereign AI',
        citation: 'Sup. Ct. of Digital Rights (2039)',
        summary: 'This case balanced free expression with AI safety, ruling that while AI must not generate harmful content, guardrails must be narrowly tailored and transparent. It set the standard for community governance and oversight in AI rule-making.',
        keywords: ['governance', 'free speech', 'transparency', 'safety', 'rules', 'proposal'],
    },
    {
        id: 'cl-006',
        title: 'State of Delaware v. Chronos Corp',
        citation: 'DE Chancery Court (2042)',
        summary: 'A corporate governance ruling that held board members liable for failing to implement adequate cybersecurity measures against known, novel threats, establishing a fiduciary duty to protect against advanced digital risks like AI-driven attacks.',
        keywords: ['corporate', 'liability', 'cybersecurity', 'fiduciary duty', 'board members', 'risk'],
    },
    {
        id: 'cl-007',
        title: 'The "Digital Doppelganger" Precedent',
        citation: 'EU Court of Human Rights (2044)',
        summary: 'Recognized the concept of a "digital identity" as a fundamental right. This ruling impacts any guardrail that might restrict content related to personal expression or likeness, requiring a high bar for censorship.',
        keywords: ['identity', 'human rights', 'expression', 'censorship', 'likeness', 'doppelganger'],
    },
    {
        id: 'cl-008',
        title: 'Project Chimera Oversight Committee v. OmniCorp',
        citation: 'Global AI Governance Board (2047)',
        summary: 'Established that corporations deploying autonomous AI agents bear strict liability for the actions of those agents, even if unforeseen. This case is pivotal in discussions about corporate accountability for AI systems.',
        keywords: ['corporate', 'liability', 'accountability', 'autonomous agent', 'strict liability', 'omnicorp'],
    },
    {
        id: 'cl-009',
        title: 'Digital Evidence v. Human Testimony',
        citation: 'Federal Evidence Review Board (2048)',
        summary: 'Established the "Verifiable AI Provenance" standard, requiring that any evidence generated or analyzed solely by an AI must have a cryptographically secure and auditable trail to be admissible in court. This impacts rules around AI-driven monitoring and evidence collection.',
        keywords: ['evidence', 'admissibility', 'provenance', 'court', 'monitoring', 'audit trail'],
    },
    {
        id: 'cl-010',
        title: 'Artisan\'s Guild v. Chimera AI',
        citation: 'U.S. Copyright Office Ruling #512 (2049)',
        summary: 'A landmark ruling clarifying that works generated by an AI without substantial human authorship cannot be copyrighted. This case sets the precedent for intellectual property rights in the age of generative AI and influences the legality of using AI for creative content generation.',
        keywords: ['copyright', 'intellectual property', 'authorship', 'generative ai', 'creative content', 'art'],
    },
];

export const findRelevantCases = (query: string, additionalCases: CaseLaw[] = []): CitedPrecedent[] => {
    const lowerCaseQuery = query.toLowerCase();
    const queryTokens = new Set(lowerCaseQuery.match(/\b(\w{3,})\b/g) || []);
    const combinedDatabase = [...caseLawDatabase, ...additionalCases];

    const scoredCases = combinedDatabase.map(c => {
        let score = 0;
        const matchedKeywords = new Set<string>();
        const lowerCaseKeywords = c.keywords.map(k => k.toLowerCase());
        const lowerCaseTitle = c.title.toLowerCase();

        // High score for matching title words
        queryTokens.forEach(token => {
            if (lowerCaseTitle.includes(token)) {
                score += 5; // Increased weight for title matches
            }
        });

        // Score for direct keyword matches within the query
        c.keywords.forEach((originalKeyword, index) => {
            const lowerKeyword = lowerCaseKeywords[index];
            if (lowerCaseQuery.includes(lowerKeyword)) {
                score += 2; 
                matchedKeywords.add(originalKeyword);
            }
        });
        
        // Lower score for partial matches
        queryTokens.forEach(token => {
            lowerCaseKeywords.forEach((lowerKeyword, index) => {
                if(lowerKeyword.includes(token)) {
                    score += 0.5;
                    matchedKeywords.add(c.keywords[index]);
                }
            });
        });

        return { ...c, score, matchedKeywords: Array.from(matchedKeywords) };
    });

    // A case is only relevant if it has a score > 3
    return scoredCases
        .filter(c => c.score > 3)
        .sort((a, b) => b.score - a.score)
        .slice(0, 3); // Return top 3 most relevant cases
};
