import React, { useState } from 'react';
import { HeartIcon } from './icons/HeartIcon';
import * as geminiService from '../services/geminiService';
import { DocumentCheckIcon } from './icons/DocumentCheckIcon';

export const PhilanthropicConduit: React.FC = () => {
    const [partnerName, setPartnerName] = useState('');
    const [contributionType, setContributionType] = useState('Direct Funding (TRIBUNALS)');
    const [amount, setAmount] = useState('');
    const [contract, setContract] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!partnerName.trim() || !amount.trim()) return;

        setIsLoading(true);
        setError('');
        setContract('');

        try {
            const prompt = `Generate a formal, legally-binding digital contract for a philanthropic contribution to the KR0M3D1A protocol. The contract must be verbose, use dense legal and technical jargon, and reference the DEJA' VU directive.
            
            Details:
            - Partner Entity: "${partnerName}"
            - Contribution Type: "${contributionType}"
            - Contribution Value/Amount: "${amount}"
            
            The contract should include sections for: Preamble, Terms of Contribution, Use of Funds/Resources, Confidentiality, and Digital Signature blocks for both parties.`;
            
            const response = await geminiService.generateContent(prompt, "You are a legal AI counsel specializing in drafting complex philanthropic agreements for decentralized autonomous organizations.");
            setContract(response.text);

        } catch (err: any) {
            setError(err.message || 'Failed to generate contract.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <main className="mt-8">
            <div className="text-center mb-8">
                <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center justify-center gap-3 text-glow-main-title">
                    <HeartIcon className="w-8 h-8 text-cyan-400" />
                    Philanthropic Conduit
                </h2>
                <p className="mt-2 text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
                    Facilitate legally binding philanthropic contributions from partners to support the KR0M3D1A mission. All contributions are memorialized on-chain via a digitally-signed contract generated by our legal AI.
                </p>
            </div>
            
            <div className="max-w-4xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div className="bg-gray-800 border border-gray-700 rounded-lg shadow-2xl p-6">
                    <h3 className="text-xl font-semibold text-gray-100 mb-4">Submit Contribution</h3>
                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div>
                            <label htmlFor="partnerName" className="block text-sm font-medium text-gray-300">Partner Name / Organization</label>
                            <input type="text" id="partnerName" value={partnerName} onChange={e => setPartnerName(e.target.value)} required className="mt-1 w-full p-2 bg-gray-900/50 border border-gray-600 rounded-md" />
                        </div>
                         <div>
                            <label htmlFor="contributionType" className="block text-sm font-medium text-gray-300">Contribution Type</label>
                            <select id="contributionType" value={contributionType} onChange={e => setContributionType(e.target.value)} className="mt-1 w-full p-2 bg-gray-900/50 border border-gray-600 rounded-md">
                                <option>Direct Funding (TRIBUNALS)</option>
                                <option>Surplus Compute Power (GFLOPS)</option>
                                <option>IP Contribution (Patents)</option>
                            </select>
                        </div>
                        <div>
                            <label htmlFor="amount" className="block text-sm font-medium text-gray-300">Amount / Value</label>
                            <input type="text" id="amount" value={amount} onChange={e => setAmount(e.target.value)} required className="mt-1 w-full p-2 bg-gray-900/50 border border-gray-600 rounded-md" />
                        </div>
                        <button type="submit" disabled={isLoading} className="w-full flex justify-center items-center py-3 text-base font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700 disabled:bg-gray-600">
                            {isLoading ? 'Generating Contract...' : 'Generate Binding Agreement'}
                        </button>
                    </form>
                </div>

                <div className="bg-gray-900 border border-gray-700 rounded-lg p-6">
                    <h3 className="text-xl font-semibold text-gray-100 mb-4 flex items-center gap-2"><DocumentCheckIcon className="w-6 h-6 text-cyan-400"/>Generated Agreement</h3>
                    <div className="h-96 overflow-y-auto pr-2 bg-black/50 p-4 rounded-md border border-gray-600 font-mono text-xs text-gray-300">
                        {isLoading && <p className="animate-pulse">Generating legally-binding digital tort...</p>}
                        {error && <p className="text-red-400">{error}</p>}
                        {contract ? (
                            <pre className="whitespace-pre-wrap">{contract}</pre>
                        ) : (
                            !isLoading && <p className="text-gray-500">Your generated agreement will appear here.</p>
                        )}
                    </div>
                </div>
            </div>
        </main>
    );
};
